name: PyTest

on:
  pull_request:
  push:
    branches: [main]

jobs:

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          $CONDA/bin/conda env create --file environment.yml --name pytest
      - name: Test with pytest
        run: |
          $CONDA/bin/conda install -n pytest -c anaconda pytest
          $CONDA/bin/conda run -n pytest pytest tests/ --doctest-modules
